### ISSUE TITLE
listing_08_11-14-cloudbees-extensions

### ISSUE THREAD

**Issue by zaze8736** [bmuschko/gradle-in-action-source#6]
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'listing_08_11-14-cloudbees-extensions'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:148)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: groovy.lang.MissingPropertyException: Could not find property 'apiKey' on root project 'listing_08_11-14-cloudbees-extensions'.
	at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
	at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:94)
	at org.gradle.api.internal.project.DefaultProject_Decorated.getProperty(Unknown Source)
	at build_59xa6eod6cbsn7ddxx37qy40r$_run_closure1.doCall(/Users/Marshall/Documents/Books/Gradle/Gradle in action/gradle-in-action-source-master/chapter08/listing_08_11-14-cloudbees-extensions/build.gradle:13)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_59xa6eod6cbsn7ddxx37qy40r.run(/Users/Marshall/Documents/Books/Gradle/Gradle in action/gradle-in-action-source-master/chapter08/listing_08_11-14-cloudbees-extensions/build.gradle:11)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 32 more

**Comment by bmuschko** [comment]
You'd have to give more information to allow me to identify your issue.

* Are you executing the listing with the [provided Wrapper](https://github.com/bmuschko/gradle-in-action-source/blob/master/gradlew) checked into the source code repository? 
* What task are you executing?

**Comment by zaze8736** [comment]
I found the property named conventionMapping in ConventionTask witch extends DefaultTask. Why the property can use in the CloudBeesTask?

**Comment by bmuschko** [comment]
There's some internal magic going on in `DefaultTask` that makes it available. It's not directly visible from the API. That's not your problem though. If you can, please provide answers to my questions and we can go from there.

**Comment by zaze8736** [comment]
I change gradle version from 1.7 to 2.2.1, and just run **gradle** using command line

**Comment by bmuschko** [comment]
The code examples might not be compatible with newer versions of Gradle. What I am seeing with Gradle 2.2.1 is the following error message:

```Could not instantiate global transform class org.spockframework.compiler.SpockTransform specified at jar:file:/Users/bmuschko/.gradle/caches/modules-2/files-2.1/org.spockframework/spock-core/0.6-groovy-1.8/5c1bfb5058c3659ddc206052601704ccd30133a5/spock-core-0.6-groovy-1.8.jar!/META-INF/services/org.codehaus.groovy.transform.ASTTransformation  because of exception org.spockframework.util.IncompatibleGroovyVersionException: The Spock compiler plugin cannot execute because Spock 0.6.0-groovy-1.8 is not compatible with Groovy 2.3.6. For more information, see http://versioninfo.spockframework.org
Spock location: file:/Users/bmuschko/.gradle/caches/modules-2/files-2.1/org.spockframework/spock-core/0.6-groovy-1.8/5c1bfb5058c3659ddc206052601704ccd30133a5/spock-core-0.6-groovy-1.8.jar
Groovy location: file:/Users/bmuschko/dev/tools/gradle-2.2.1/lib/groovy-all-2.3.6.jar```

This indicates that the version of Spock used in `buildSrc` is not compatible with the version of Groovy bundled with Gradle anymore. If you want to go ahead and use a newer version of Gradle, you'd need to upgrade Spock.

**Comment by zaze8736** [comment]
**Thanks**, I got it.
